### ISSUE TITLE
'mds-persian-datetime' not found

### ISSUE THREAD

**Issue by mekramy** [Mds92/mds-persian-calendar-npm-package#1]
Hi,
Please fix your documentation, your package is 'mds.persian.datetime' not 'mds-persian-datetime'

**Comment by Mds92** [comment]
Where did I write `mds-persian-datetime`  to install package !
I wrote `npm install mds.persian.datetime --save` !!!

**Comment by mekramy** [comment]
you use this in usage guide not in installation. this lines:
```
import { Mds } from 'mds-persian-datetime'
import PersianDateTime = Mds.PersianDateTime;
```

must fixed to:
```
import { Mds } from 'mds.persian.datetime'
import PersianDateTime = Mds.PersianDateTime;
```

**Comment by Mds92** [comment]
Oops, you're right
I just fixed it

**Comment by mekramy** [comment]
Tnx. Your library very usefull


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Mohammmad Dayyan <notifications@github.com> Date: 8/28/17  11:00 AM  (GMT+03:30) To: Mds92/mds-persian-datetime-package <mds-persian-datetime-package@noreply.github.com> Cc: Mojtaba ajamekramy <m.ajamekramy@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Mds92/mds-persian-datetime-package] 'mds-persian-datetime' not found (#1) 
Ooops, you're right

I just fixed it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mds92/mds-persian-datetime-package","title":"Mds92/mds-persian-datetime-package","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Mds92/mds-persian-datetime-package"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Mds92 in #1: Ooops, you're right\r\nI just fixed it"}],"action":{"name":"View Issue","url":"https://github.com/Mds92/mds-persian-datetime-package/issues/1#issuecomment-325270892"}}}
